2025-09-25 22:00:34,737 INFO: Future Mech startup [in d:\future mech\app.py:72]
2025-09-25 22:00:34,778 ERROR: Initialization error: 'NoneType' object has no attribute 'cursor' [in d:\future mech\app.py:1901]
2025-09-25 22:00:37,402 INFO: Future Mech startup [in d:\future mech\app.py:72]
2025-09-25 22:00:37,441 ERROR: Initialization error: 'NoneType' object has no attribute 'cursor' [in d:\future mech\app.py:1901]
2025-09-25 22:03:17,684 ERROR: Email sending failed: (535, b'5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials 98e67ed59e1d1-33474b1a2e3sm2874384a91.22 - gsmtp') [in d:\future mech\app.py:120]
2025-10-05 18:39:32,091 INFO: Future Mech startup [in d:\future mech\app.py:72]
2025-10-05 18:39:32,164 ERROR: Initialization error: 'NoneType' object has no attribute 'cursor' [in d:\future mech\app.py:1901]
2025-10-05 18:39:35,186 INFO: Future Mech startup [in d:\future mech\app.py:72]
2025-10-05 18:39:35,223 ERROR: Initialization error: 'NoneType' object has no attribute 'cursor' [in d:\future mech\app.py:1901]
2025-10-05 20:15:45,464 INFO: Future Mech startup [in d:\future mech\app.py:72]
2025-10-05 20:15:45,504 ERROR: Initialization error: 'NoneType' object has no attribute 'cursor' [in d:\future mech\app.py:1951]
2025-10-05 20:15:47,733 INFO: Future Mech startup [in d:\future mech\app.py:72]
2025-10-05 20:15:47,773 ERROR: Initialization error: 'NoneType' object has no attribute 'cursor' [in d:\future mech\app.py:1951]
2025-10-06 21:37:13,480 INFO: Future Mech startup [in d:\future mech\app.py:72]
2025-10-06 21:37:13,512 ERROR: Initialization error: 'NoneType' object has no attribute 'cursor' [in d:\future mech\app.py:1951]
2025-10-06 21:37:15,715 INFO: Future Mech startup [in d:\future mech\app.py:72]
2025-10-06 21:37:15,765 ERROR: Initialization error: 'NoneType' object has no attribute 'cursor' [in d:\future mech\app.py:1951]
2025-10-06 21:53:53,983 INFO: Future Mech startup [in d:\future mech\app.py:72]
2025-10-06 21:53:54,005 ERROR: Initialization error: 'NoneType' object has no attribute 'cursor' [in d:\future mech\app.py:1951]
2025-10-06 22:33:11,013 INFO: Future Mech startup [in d:\future mech\app.py:72]
2025-10-06 22:33:11,069 ERROR: Initialization error: 'NoneType' object has no attribute 'cursor' [in d:\future mech\app.py:1954]
2025-10-06 22:34:57,869 INFO: Future Mech startup [in d:\future mech\app.py:72]
2025-10-06 22:34:57,898 ERROR: Initialization error: 'NoneType' object has no attribute 'cursor' [in d:\future mech\app.py:2030]
2025-10-07 21:09:16,704 INFO: Future Mech startup [in d:\future mech\app.py:72]
2025-10-07 21:09:16,749 ERROR: Initialization error: 'NoneType' object has no attribute 'cursor' [in d:\future mech\app.py:2030]
2025-10-07 21:09:19,674 INFO: Future Mech startup [in d:\future mech\app.py:72]
2025-10-07 21:09:19,720 ERROR: Initialization error: 'NoneType' object has no attribute 'cursor' [in d:\future mech\app.py:2030]
2025-10-07 22:03:19,862 ERROR: Create notification error: (1054, "Unknown column 'role' in 'field list'") [in d:\future mech\app.py:1540]
2025-10-07 22:03:52,912 ERROR: Add service error: (1366, "Incorrect integer value: 'true' for column 'is_active' at row 1") [in d:\future mech\app.py:1736]
2025-10-07 22:04:06,732 ERROR: Add service error: (1366, "Incorrect integer value: 'true' for column 'is_active' at row 1") [in d:\future mech\app.py:1736]
2025-10-07 22:04:13,906 ERROR: Add service error: (1366, "Incorrect integer value: 'true' for column 'is_featured' at row 1") [in d:\future mech\app.py:1736]
2025-10-07 22:04:35,858 ERROR: Add service error: (1366, "Incorrect integer value: 'true' for column 'is_active' at row 1") [in d:\future mech\app.py:1736]
2025-10-07 22:04:47,313 ERROR: Add service error: (1366, "Incorrect integer value: 'true' for column 'is_active' at row 1") [in d:\future mech\app.py:1736]
2025-10-07 22:05:04,592 ERROR: Add service error: (1366, "Incorrect integer value: 'true' for column 'is_featured' at row 1") [in d:\future mech\app.py:1736]
2025-10-07 22:06:51,247 ERROR: Add service error: (1366, "Incorrect integer value: 'true' for column 'is_active' at row 1") [in d:\future mech\app.py:1736]
2025-10-07 22:58:11,759 INFO: Future Mech startup [in d:\future mech\app.py:72]
2025-10-07 22:58:11,810 ERROR: Initialization error: 'NoneType' object has no attribute 'cursor' [in d:\future mech\app.py:2066]
2025-10-07 22:59:20,442 INFO: Service added successfully: battery B16 , ID: 28 [in d:\future mech\app.py:1743]
2025-10-07 22:59:20,445 INFO: Service added successfully: battery B16 , ID: 29 [in d:\future mech\app.py:1743]
2025-10-08 21:37:45,553 INFO: Future Mech startup [in D:\future mech\app.py:72]
2025-10-08 21:37:45,568 ERROR: Initialization error: 'NoneType' object has no attribute 'cursor' [in D:\future mech\app.py:2066]
2025-10-08 21:37:46,539 INFO: Future Mech startup [in D:\future mech\app.py:72]
2025-10-08 21:37:46,554 ERROR: Initialization error: 'NoneType' object has no attribute 'cursor' [in D:\future mech\app.py:2066]
2025-10-08 21:44:49,978 ERROR: Email sending failed: (535, b'5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials d9443c01a7336-29034f36738sm1358255ad.87 - gsmtp') [in D:\future mech\app.py:120]
2025-10-08 21:51:22,165 ERROR: API add vehicle error: (1062, "Duplicate entry 'ewkj' for key 'vehicles.registration_no'") [in D:\future mech\app.py:1651]
2025-10-08 22:18:24,695 INFO: Future Mech startup [in D:\future mech\app.py:72]
2025-10-08 22:18:24,710 ERROR: Initialization error: 'NoneType' object has no attribute 'cursor' [in D:\future mech\app.py:2074]
2025-10-08 22:19:34,217 INFO: Future Mech startup [in D:\future mech\app.py:72]
2025-10-08 22:19:34,232 ERROR: Initialization error: 'NoneType' object has no attribute 'cursor' [in D:\future mech\app.py:2114]
2025-10-08 22:20:44,764 INFO: Future Mech startup [in D:\future mech\app.py:72]
2025-10-08 22:20:44,779 ERROR: Initialization error: 'NoneType' object has no attribute 'cursor' [in D:\future mech\app.py:2123]
2025-10-08 22:21:37,706 ERROR: API add vehicle error: (1452, 'Cannot add or update a child row: a foreign key constraint fails (`future_mech_db`.`vehicles`, CONSTRAINT `vehicles_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE)') [in D:\future mech\app.py:1707]
2025-10-15 21:14:53,546 INFO: Future Mech startup [in d:\future mech\app.py:72]
2025-10-15 21:14:53,633 ERROR: Initialization error: 'NoneType' object has no attribute 'cursor' [in d:\future mech\app.py:2123]
2025-10-15 21:14:58,347 INFO: Future Mech startup [in d:\future mech\app.py:72]
2025-10-15 21:14:58,409 ERROR: Initialization error: 'NoneType' object has no attribute 'cursor' [in d:\future mech\app.py:2123]
2025-10-15 21:25:48,209 INFO: Service added successfully: rikvendra, ID: 17 [in d:\future mech\app.py:1800]
2025-10-15 21:25:48,212 INFO: Service added successfully: rikvendra, ID: 18 [in d:\future mech\app.py:1800]
2025-10-15 21:26:23,759 ERROR: Create notification error: (1054, "Unknown column 'role' in 'field list'") [in d:\future mech\app.py:1549]
2025-10-15 21:26:23,759 ERROR: Create notification error: (1054, "Unknown column 'role' in 'field list'") [in d:\future mech\app.py:1549]
2025-10-15 21:26:23,760 INFO: Car part added successfully: admin, ID: 9 [in d:\future mech\app.py:1911]
2025-10-15 21:26:23,761 INFO: Car part added successfully: admin, ID: 10 [in d:\future mech\app.py:1911]
2025-10-15 21:27:18,201 ERROR: Create notification error: (1054, "Unknown column 'role' in 'field list'") [in d:\future mech\app.py:1549]
2025-10-15 21:27:18,202 INFO: Car part added successfully: battery B16 , ID: 11 [in d:\future mech\app.py:1911]
2025-10-15 21:27:18,202 ERROR: Create notification error: (1054, "Unknown column 'role' in 'field list'") [in d:\future mech\app.py:1549]
2025-10-15 21:27:18,206 INFO: Car part added successfully: battery B16 , ID: 12 [in d:\future mech\app.py:1911]
2025-10-16 10:38:28,643 INFO: Future Mech startup [in F:\Future Mech\Future-Mech\app.py:72]
2025-10-16 10:38:28,671 ERROR: Initialization error: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information. [in F:\Future Mech\Future-Mech\app.py:2123]
2025-10-16 10:38:34,111 INFO: Future Mech startup [in F:\Future Mech\Future-Mech\app.py:72]
2025-10-16 10:38:34,156 ERROR: Initialization error: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information. [in F:\Future Mech\Future-Mech\app.py:2123]
2025-10-16 10:38:46,326 ERROR: Error loading home page: (2002, "Can't connect to server on 'localhost' (10061)") [in F:\Future Mech\Future-Mech\app.py:365]
2025-10-16 11:08:32,780 ERROR: Error loading home page: (2002, "Can't connect to server on 'localhost' (10061)") [in F:\Future Mech\Future-Mech\app.py:365]
2025-10-16 11:13:18,131 ERROR: Error loading home page: (2002, "Can't connect to server on 'localhost' (10061)") [in F:\Future Mech\Future-Mech\app.py:365]
2025-10-16 11:25:13,711 ERROR: Error loading car parts: (2002, "Can't connect to server on 'localhost' (10061)") [in F:\Future Mech\Future-Mech\app.py:412]
2025-10-16 11:25:23,979 ERROR: Error loading car parts: (2002, "Can't connect to server on 'localhost' (10061)") [in F:\Future Mech\Future-Mech\app.py:412]
2025-10-16 11:25:26,777 ERROR: Error loading services: (2002, "Can't connect to server on 'localhost' (10061)") [in F:\Future Mech\Future-Mech\app.py:378]
2025-10-16 11:25:36,024 ERROR: Error loading home page: (2002, "Can't connect to server on 'localhost' (10061)") [in F:\Future Mech\Future-Mech\app.py:365]
